[env:tbeam_axp2101_sx1278]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.38-1/platform-espressif32.zip
board = esp32dev
framework = arduino

board_build.filesystem = littlefs
board_build.partitions = min_spiffs.csv

monitor_speed = 115200
upload_speed = 115200

lib_deps =
    jgromes/RadioLib
    lewisxhe/XPowersLib
    olikraus/U8g2
    mikalhart/TinyGPSPlus

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DRADIOLIB_GODMODE=1
